// Copyright 2019, Beeswax.IO Inc.
// Author gil@beeswax.com
//
// Constraints on an exchange seat for a BidRequest

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.3
// source: beeswax/openrtb/seat_constraints.proto

package openrtb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Next available tag: 2
type SeatConstraints struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BidFloorMicros *int64                 `protobuf:"varint,1,opt,name=bid_floor_micros,json=bidFloorMicros,def=0" json:"bid_floor_micros,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

// Default values for SeatConstraints fields.
const (
	Default_SeatConstraints_BidFloorMicros = int64(0)
)

func (x *SeatConstraints) Reset() {
	*x = SeatConstraints{}
	mi := &file_beeswax_openrtb_seat_constraints_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatConstraints) ProtoMessage() {}

func (x *SeatConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_openrtb_seat_constraints_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatConstraints.ProtoReflect.Descriptor instead.
func (*SeatConstraints) Descriptor() ([]byte, []int) {
	return file_beeswax_openrtb_seat_constraints_proto_rawDescGZIP(), []int{0}
}

func (x *SeatConstraints) GetBidFloorMicros() int64 {
	if x != nil && x.BidFloorMicros != nil {
		return *x.BidFloorMicros
	}
	return Default_SeatConstraints_BidFloorMicros
}

var File_beeswax_openrtb_seat_constraints_proto protoreflect.FileDescriptor

const file_beeswax_openrtb_seat_constraints_proto_rawDesc = "" +
	"\n" +
	"&beeswax/openrtb/seat_constraints.proto\x12\aopenrtb\">\n" +
	"\x0fSeatConstraints\x12+\n" +
	"\x10bid_floor_micros\x18\x01 \x01(\x03:\x010R\x0ebidFloorMicrosB\x18\n" +
	"\x13com.beeswax.openrtb\xf8\x01\x01"

var (
	file_beeswax_openrtb_seat_constraints_proto_rawDescOnce sync.Once
	file_beeswax_openrtb_seat_constraints_proto_rawDescData []byte
)

func file_beeswax_openrtb_seat_constraints_proto_rawDescGZIP() []byte {
	file_beeswax_openrtb_seat_constraints_proto_rawDescOnce.Do(func() {
		file_beeswax_openrtb_seat_constraints_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beeswax_openrtb_seat_constraints_proto_rawDesc), len(file_beeswax_openrtb_seat_constraints_proto_rawDesc)))
	})
	return file_beeswax_openrtb_seat_constraints_proto_rawDescData
}

var file_beeswax_openrtb_seat_constraints_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_beeswax_openrtb_seat_constraints_proto_goTypes = []any{
	(*SeatConstraints)(nil), // 0: openrtb.SeatConstraints
}
var file_beeswax_openrtb_seat_constraints_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_beeswax_openrtb_seat_constraints_proto_init() }
func file_beeswax_openrtb_seat_constraints_proto_init() {
	if File_beeswax_openrtb_seat_constraints_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beeswax_openrtb_seat_constraints_proto_rawDesc), len(file_beeswax_openrtb_seat_constraints_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_beeswax_openrtb_seat_constraints_proto_goTypes,
		DependencyIndexes: file_beeswax_openrtb_seat_constraints_proto_depIdxs,
		MessageInfos:      file_beeswax_openrtb_seat_constraints_proto_msgTypes,
	}.Build()
	File_beeswax_openrtb_seat_constraints_proto = out.File
	file_beeswax_openrtb_seat_constraints_proto_goTypes = nil
	file_beeswax_openrtb_seat_constraints_proto_depIdxs = nil
}
