// Copyright 2015, Beeswax.IO Inc.
// Author: ramr@beeswax.com
//
// Protocol buffer defining a unique EventId

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.3
// source: beeswax/base/eventid.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 32 bits of md5 hash
	Hostid    *uint32 `protobuf:"varint,1,opt,name=hostid" json:"hostid,omitempty"`
	Tid       *uint32 `protobuf:"varint,2,opt,name=tid" json:"tid,omitempty"`
	Timestamp *uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	// Impression index within the request
	ImpIdx        *uint32 `protobuf:"varint,4,opt,name=imp_idx,json=impIdx" json:"imp_idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventId) Reset() {
	*x = EventId{}
	mi := &file_beeswax_base_eventid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventId) ProtoMessage() {}

func (x *EventId) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_base_eventid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventId.ProtoReflect.Descriptor instead.
func (*EventId) Descriptor() ([]byte, []int) {
	return file_beeswax_base_eventid_proto_rawDescGZIP(), []int{0}
}

func (x *EventId) GetHostid() uint32 {
	if x != nil && x.Hostid != nil {
		return *x.Hostid
	}
	return 0
}

func (x *EventId) GetTid() uint32 {
	if x != nil && x.Tid != nil {
		return *x.Tid
	}
	return 0
}

func (x *EventId) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *EventId) GetImpIdx() uint32 {
	if x != nil && x.ImpIdx != nil {
		return *x.ImpIdx
	}
	return 0
}

// Next Tag: 5
type AdGroupId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuzzKey       *string                `protobuf:"bytes,1,opt,name=buzz_key,json=buzzKey" json:"buzz_key,omitempty"`
	Accountid     *uint64                `protobuf:"varint,2,opt,name=accountid" json:"accountid,omitempty"`
	Campaignid    *uint64                `protobuf:"varint,3,opt,name=campaignid" json:"campaignid,omitempty"`
	Lineitemid    *uint64                `protobuf:"varint,4,opt,name=lineitemid" json:"lineitemid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdGroupId) Reset() {
	*x = AdGroupId{}
	mi := &file_beeswax_base_eventid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdGroupId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdGroupId) ProtoMessage() {}

func (x *AdGroupId) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_base_eventid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdGroupId.ProtoReflect.Descriptor instead.
func (*AdGroupId) Descriptor() ([]byte, []int) {
	return file_beeswax_base_eventid_proto_rawDescGZIP(), []int{1}
}

func (x *AdGroupId) GetBuzzKey() string {
	if x != nil && x.BuzzKey != nil {
		return *x.BuzzKey
	}
	return ""
}

func (x *AdGroupId) GetAccountid() uint64 {
	if x != nil && x.Accountid != nil {
		return *x.Accountid
	}
	return 0
}

func (x *AdGroupId) GetCampaignid() uint64 {
	if x != nil && x.Campaignid != nil {
		return *x.Campaignid
	}
	return 0
}

func (x *AdGroupId) GetLineitemid() uint64 {
	if x != nil && x.Lineitemid != nil {
		return *x.Lineitemid
	}
	return 0
}

var File_beeswax_base_eventid_proto protoreflect.FileDescriptor

const file_beeswax_base_eventid_proto_rawDesc = "" +
	"\n" +
	"\x1abeeswax/base/eventid.proto\x12\x04base\"j\n" +
	"\aEventId\x12\x16\n" +
	"\x06hostid\x18\x01 \x01(\rR\x06hostid\x12\x10\n" +
	"\x03tid\x18\x02 \x01(\rR\x03tid\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12\x17\n" +
	"\aimp_idx\x18\x04 \x01(\rR\x06impIdx\"\x84\x01\n" +
	"\tAdGroupId\x12\x19\n" +
	"\bbuzz_key\x18\x01 \x01(\tR\abuzzKey\x12\x1c\n" +
	"\taccountid\x18\x02 \x01(\x04R\taccountid\x12\x1e\n" +
	"\n" +
	"campaignid\x18\x03 \x01(\x04R\n" +
	"campaignid\x12\x1e\n" +
	"\n" +
	"lineitemid\x18\x04 \x01(\x04R\n" +
	"lineitemidB\x12\n" +
	"\x10com.beeswax.base"

var (
	file_beeswax_base_eventid_proto_rawDescOnce sync.Once
	file_beeswax_base_eventid_proto_rawDescData []byte
)

func file_beeswax_base_eventid_proto_rawDescGZIP() []byte {
	file_beeswax_base_eventid_proto_rawDescOnce.Do(func() {
		file_beeswax_base_eventid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beeswax_base_eventid_proto_rawDesc), len(file_beeswax_base_eventid_proto_rawDesc)))
	})
	return file_beeswax_base_eventid_proto_rawDescData
}

var file_beeswax_base_eventid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_beeswax_base_eventid_proto_goTypes = []any{
	(*EventId)(nil),   // 0: base.EventId
	(*AdGroupId)(nil), // 1: base.AdGroupId
}
var file_beeswax_base_eventid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_beeswax_base_eventid_proto_init() }
func file_beeswax_base_eventid_proto_init() {
	if File_beeswax_base_eventid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beeswax_base_eventid_proto_rawDesc), len(file_beeswax_base_eventid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_beeswax_base_eventid_proto_goTypes,
		DependencyIndexes: file_beeswax_base_eventid_proto_depIdxs,
		MessageInfos:      file_beeswax_base_eventid_proto_msgTypes,
	}.Build()
	File_beeswax_base_eventid_proto = out.File
	file_beeswax_base_eventid_proto_goTypes = nil
	file_beeswax_base_eventid_proto_depIdxs = nil
}
