// Copyright 2022, Beeswax.IO Inc.
//
// Protocol buffer defining BidShadingInfo

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.3
// source: beeswax/stinger/adgroup.proto

package stinger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidShadingFee_BidShadingFeeType int32

const (
	BidShadingFee_UNKNOWN              BidShadingFee_BidShadingFeeType = 0
	BidShadingFee_VENDOR_FEE           BidShadingFee_BidShadingFeeType = 1
	BidShadingFee_INCLUDED_IN_WINPRICE BidShadingFee_BidShadingFeeType = 2
)

// Enum value maps for BidShadingFee_BidShadingFeeType.
var (
	BidShadingFee_BidShadingFeeType_name = map[int32]string{
		0: "UNKNOWN",
		1: "VENDOR_FEE",
		2: "INCLUDED_IN_WINPRICE",
	}
	BidShadingFee_BidShadingFeeType_value = map[string]int32{
		"UNKNOWN":              0,
		"VENDOR_FEE":           1,
		"INCLUDED_IN_WINPRICE": 2,
	}
)

func (x BidShadingFee_BidShadingFeeType) Enum() *BidShadingFee_BidShadingFeeType {
	p := new(BidShadingFee_BidShadingFeeType)
	*p = x
	return p
}

func (x BidShadingFee_BidShadingFeeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BidShadingFee_BidShadingFeeType) Descriptor() protoreflect.EnumDescriptor {
	return file_beeswax_stinger_adgroup_proto_enumTypes[0].Descriptor()
}

func (BidShadingFee_BidShadingFeeType) Type() protoreflect.EnumType {
	return &file_beeswax_stinger_adgroup_proto_enumTypes[0]
}

func (x BidShadingFee_BidShadingFeeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *BidShadingFee_BidShadingFeeType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = BidShadingFee_BidShadingFeeType(num)
	return nil
}

// Deprecated: Use BidShadingFee_BidShadingFeeType.Descriptor instead.
func (BidShadingFee_BidShadingFeeType) EnumDescriptor() ([]byte, []int) {
	return file_beeswax_stinger_adgroup_proto_rawDescGZIP(), []int{0, 0}
}

type BidShadingInfo_BidGroup int32

const (
	BidShadingInfo_UNKNOWN BidShadingInfo_BidGroup = 0
	BidShadingInfo_CONTROL BidShadingInfo_BidGroup = 1
	BidShadingInfo_TEST    BidShadingInfo_BidGroup = 2
)

// Enum value maps for BidShadingInfo_BidGroup.
var (
	BidShadingInfo_BidGroup_name = map[int32]string{
		0: "UNKNOWN",
		1: "CONTROL",
		2: "TEST",
	}
	BidShadingInfo_BidGroup_value = map[string]int32{
		"UNKNOWN": 0,
		"CONTROL": 1,
		"TEST":    2,
	}
)

func (x BidShadingInfo_BidGroup) Enum() *BidShadingInfo_BidGroup {
	p := new(BidShadingInfo_BidGroup)
	*p = x
	return p
}

func (x BidShadingInfo_BidGroup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BidShadingInfo_BidGroup) Descriptor() protoreflect.EnumDescriptor {
	return file_beeswax_stinger_adgroup_proto_enumTypes[1].Descriptor()
}

func (BidShadingInfo_BidGroup) Type() protoreflect.EnumType {
	return &file_beeswax_stinger_adgroup_proto_enumTypes[1]
}

func (x BidShadingInfo_BidGroup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *BidShadingInfo_BidGroup) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = BidShadingInfo_BidGroup(num)
	return nil
}

// Deprecated: Use BidShadingInfo_BidGroup.Descriptor instead.
func (BidShadingInfo_BidGroup) EnumDescriptor() ([]byte, []int) {
	return file_beeswax_stinger_adgroup_proto_rawDescGZIP(), []int{1, 0}
}

type BidShadingInfo_BidShadeState int32

const (
	BidShadingInfo_NOT_ELIGIBLE  BidShadingInfo_BidShadeState = 0
	BidShadingInfo_CONTROL_GROUP BidShadingInfo_BidShadeState = 1
	BidShadingInfo_BID_SHADED    BidShadingInfo_BidShadeState = 2
	BidShadingInfo_RANDOM        BidShadingInfo_BidShadeState = 3
)

// Enum value maps for BidShadingInfo_BidShadeState.
var (
	BidShadingInfo_BidShadeState_name = map[int32]string{
		0: "NOT_ELIGIBLE",
		1: "CONTROL_GROUP",
		2: "BID_SHADED",
		3: "RANDOM",
	}
	BidShadingInfo_BidShadeState_value = map[string]int32{
		"NOT_ELIGIBLE":  0,
		"CONTROL_GROUP": 1,
		"BID_SHADED":    2,
		"RANDOM":        3,
	}
)

func (x BidShadingInfo_BidShadeState) Enum() *BidShadingInfo_BidShadeState {
	p := new(BidShadingInfo_BidShadeState)
	*p = x
	return p
}

func (x BidShadingInfo_BidShadeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BidShadingInfo_BidShadeState) Descriptor() protoreflect.EnumDescriptor {
	return file_beeswax_stinger_adgroup_proto_enumTypes[2].Descriptor()
}

func (BidShadingInfo_BidShadeState) Type() protoreflect.EnumType {
	return &file_beeswax_stinger_adgroup_proto_enumTypes[2]
}

func (x BidShadingInfo_BidShadeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *BidShadingInfo_BidShadeState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = BidShadingInfo_BidShadeState(num)
	return nil
}

// Deprecated: Use BidShadingInfo_BidShadeState.Descriptor instead.
func (BidShadingInfo_BidShadeState) EnumDescriptor() ([]byte, []int) {
	return file_beeswax_stinger_adgroup_proto_rawDescGZIP(), []int{1, 1}
}

// Next Tag: 3
type BidShadingFee struct {
	state                  protoimpl.MessageState           `protogen:"open.v1"`
	BidShadingFeeType      *BidShadingFee_BidShadingFeeType `protobuf:"varint,1,opt,name=bid_shading_fee_type,json=bidShadingFeeType,enum=stinger.BidShadingFee_BidShadingFeeType" json:"bid_shading_fee_type,omitempty"`
	BidShadingFeeMicrosUsd *int64                           `protobuf:"varint,2,opt,name=bid_shading_fee_micros_usd,json=bidShadingFeeMicrosUsd" json:"bid_shading_fee_micros_usd,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BidShadingFee) Reset() {
	*x = BidShadingFee{}
	mi := &file_beeswax_stinger_adgroup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidShadingFee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidShadingFee) ProtoMessage() {}

func (x *BidShadingFee) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_stinger_adgroup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidShadingFee.ProtoReflect.Descriptor instead.
func (*BidShadingFee) Descriptor() ([]byte, []int) {
	return file_beeswax_stinger_adgroup_proto_rawDescGZIP(), []int{0}
}

func (x *BidShadingFee) GetBidShadingFeeType() BidShadingFee_BidShadingFeeType {
	if x != nil && x.BidShadingFeeType != nil {
		return *x.BidShadingFeeType
	}
	return BidShadingFee_UNKNOWN
}

func (x *BidShadingFee) GetBidShadingFeeMicrosUsd() int64 {
	if x != nil && x.BidShadingFeeMicrosUsd != nil {
		return *x.BidShadingFeeMicrosUsd
	}
	return 0
}

// Information about bid shading like what group the event is in
// and what slice the request belongs to
// Next Tag: 6
type BidShadingInfo struct {
	state    protoimpl.MessageState   `protogen:"open.v1"`
	BidGroup *BidShadingInfo_BidGroup `protobuf:"varint,1,opt,name=bid_group,json=bidGroup,enum=stinger.BidShadingInfo_BidGroup,def=0" json:"bid_group,omitempty"`
	SliceId  *string                  `protobuf:"bytes,2,opt,name=slice_id,json=sliceId" json:"slice_id,omitempty"`
	// state of bid shading
	BidShade *BidShadingInfo_BidShadeState `protobuf:"varint,3,opt,name=bid_shade,json=bidShade,enum=stinger.BidShadingInfo_BidShadeState,def=0" json:"bid_shade,omitempty"`
	// micros we reduced the customer's bid price by.
	BidShadeReductionMicros *int64         `protobuf:"varint,4,opt,name=bid_shade_reduction_micros,json=bidShadeReductionMicros" json:"bid_shade_reduction_micros,omitempty"`
	BidShadingFee           *BidShadingFee `protobuf:"bytes,5,opt,name=bid_shading_fee,json=bidShadingFee" json:"bid_shading_fee,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

// Default values for BidShadingInfo fields.
const (
	Default_BidShadingInfo_BidGroup = BidShadingInfo_UNKNOWN
	Default_BidShadingInfo_BidShade = BidShadingInfo_NOT_ELIGIBLE
)

func (x *BidShadingInfo) Reset() {
	*x = BidShadingInfo{}
	mi := &file_beeswax_stinger_adgroup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidShadingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidShadingInfo) ProtoMessage() {}

func (x *BidShadingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_stinger_adgroup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidShadingInfo.ProtoReflect.Descriptor instead.
func (*BidShadingInfo) Descriptor() ([]byte, []int) {
	return file_beeswax_stinger_adgroup_proto_rawDescGZIP(), []int{1}
}

func (x *BidShadingInfo) GetBidGroup() BidShadingInfo_BidGroup {
	if x != nil && x.BidGroup != nil {
		return *x.BidGroup
	}
	return Default_BidShadingInfo_BidGroup
}

func (x *BidShadingInfo) GetSliceId() string {
	if x != nil && x.SliceId != nil {
		return *x.SliceId
	}
	return ""
}

func (x *BidShadingInfo) GetBidShade() BidShadingInfo_BidShadeState {
	if x != nil && x.BidShade != nil {
		return *x.BidShade
	}
	return Default_BidShadingInfo_BidShade
}

func (x *BidShadingInfo) GetBidShadeReductionMicros() int64 {
	if x != nil && x.BidShadeReductionMicros != nil {
		return *x.BidShadeReductionMicros
	}
	return 0
}

func (x *BidShadingInfo) GetBidShadingFee() *BidShadingFee {
	if x != nil {
		return x.BidShadingFee
	}
	return nil
}

var File_beeswax_stinger_adgroup_proto protoreflect.FileDescriptor

const file_beeswax_stinger_adgroup_proto_rawDesc = "" +
	"\n" +
	"\x1dbeeswax/stinger/adgroup.proto\x12\astinger\"\xf2\x01\n" +
	"\rBidShadingFee\x12Y\n" +
	"\x14bid_shading_fee_type\x18\x01 \x01(\x0e2(.stinger.BidShadingFee.BidShadingFeeTypeR\x11bidShadingFeeType\x12:\n" +
	"\x1abid_shading_fee_micros_usd\x18\x02 \x01(\x03R\x16bidShadingFeeMicrosUsd\"J\n" +
	"\x11BidShadingFeeType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"VENDOR_FEE\x10\x01\x12\x18\n" +
	"\x14INCLUDED_IN_WINPRICE\x10\x02\"\xc4\x03\n" +
	"\x0eBidShadingInfo\x12F\n" +
	"\tbid_group\x18\x01 \x01(\x0e2 .stinger.BidShadingInfo.BidGroup:\aUNKNOWNR\bbidGroup\x12\x19\n" +
	"\bslice_id\x18\x02 \x01(\tR\asliceId\x12P\n" +
	"\tbid_shade\x18\x03 \x01(\x0e2%.stinger.BidShadingInfo.BidShadeState:\fNOT_ELIGIBLER\bbidShade\x12;\n" +
	"\x1abid_shade_reduction_micros\x18\x04 \x01(\x03R\x17bidShadeReductionMicros\x12>\n" +
	"\x0fbid_shading_fee\x18\x05 \x01(\v2\x16.stinger.BidShadingFeeR\rbidShadingFee\".\n" +
	"\bBidGroup\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aCONTROL\x10\x01\x12\b\n" +
	"\x04TEST\x10\x02\"P\n" +
	"\rBidShadeState\x12\x10\n" +
	"\fNOT_ELIGIBLE\x10\x00\x12\x11\n" +
	"\rCONTROL_GROUP\x10\x01\x12\x0e\n" +
	"\n" +
	"BID_SHADED\x10\x02\x12\n" +
	"\n" +
	"\x06RANDOM\x10\x03B\x15\n" +
	"\x13com.beeswax.stinger"

var (
	file_beeswax_stinger_adgroup_proto_rawDescOnce sync.Once
	file_beeswax_stinger_adgroup_proto_rawDescData []byte
)

func file_beeswax_stinger_adgroup_proto_rawDescGZIP() []byte {
	file_beeswax_stinger_adgroup_proto_rawDescOnce.Do(func() {
		file_beeswax_stinger_adgroup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beeswax_stinger_adgroup_proto_rawDesc), len(file_beeswax_stinger_adgroup_proto_rawDesc)))
	})
	return file_beeswax_stinger_adgroup_proto_rawDescData
}

var file_beeswax_stinger_adgroup_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_beeswax_stinger_adgroup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_beeswax_stinger_adgroup_proto_goTypes = []any{
	(BidShadingFee_BidShadingFeeType)(0), // 0: stinger.BidShadingFee.BidShadingFeeType
	(BidShadingInfo_BidGroup)(0),         // 1: stinger.BidShadingInfo.BidGroup
	(BidShadingInfo_BidShadeState)(0),    // 2: stinger.BidShadingInfo.BidShadeState
	(*BidShadingFee)(nil),                // 3: stinger.BidShadingFee
	(*BidShadingInfo)(nil),               // 4: stinger.BidShadingInfo
}
var file_beeswax_stinger_adgroup_proto_depIdxs = []int32{
	0, // 0: stinger.BidShadingFee.bid_shading_fee_type:type_name -> stinger.BidShadingFee.BidShadingFeeType
	1, // 1: stinger.BidShadingInfo.bid_group:type_name -> stinger.BidShadingInfo.BidGroup
	2, // 2: stinger.BidShadingInfo.bid_shade:type_name -> stinger.BidShadingInfo.BidShadeState
	3, // 3: stinger.BidShadingInfo.bid_shading_fee:type_name -> stinger.BidShadingFee
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_beeswax_stinger_adgroup_proto_init() }
func file_beeswax_stinger_adgroup_proto_init() {
	if File_beeswax_stinger_adgroup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beeswax_stinger_adgroup_proto_rawDesc), len(file_beeswax_stinger_adgroup_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_beeswax_stinger_adgroup_proto_goTypes,
		DependencyIndexes: file_beeswax_stinger_adgroup_proto_depIdxs,
		EnumInfos:         file_beeswax_stinger_adgroup_proto_enumTypes,
		MessageInfos:      file_beeswax_stinger_adgroup_proto_msgTypes,
	}.Build()
	File_beeswax_stinger_adgroup_proto = out.File
	file_beeswax_stinger_adgroup_proto_goTypes = nil
	file_beeswax_stinger_adgroup_proto_depIdxs = nil
}
