// Copyright 2018, Beeswax.IO Inc.
//
// Currency related information

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.3
// source: beeswax/currency/currency.proto

package currency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency_Code int32

const (
	Currency_UNKNOWN Currency_Code = 0
	Currency_USD     Currency_Code = 1 // US Dollar
	Currency_EUR     Currency_Code = 2 // Euro
	Currency_GBP     Currency_Code = 3 // Pound Sterling
	Currency_CAD     Currency_Code = 4 // Canadian Dollar
	Currency_CHF     Currency_Code = 5 // Swiss Franc
	Currency_UAH     Currency_Code = 6 // Ukrainian hryvnia
	Currency_JPY     Currency_Code = 7 // Japanese Yen
)

// Enum value maps for Currency_Code.
var (
	Currency_Code_name = map[int32]string{
		0: "UNKNOWN",
		1: "USD",
		2: "EUR",
		3: "GBP",
		4: "CAD",
		5: "CHF",
		6: "UAH",
		7: "JPY",
	}
	Currency_Code_value = map[string]int32{
		"UNKNOWN": 0,
		"USD":     1,
		"EUR":     2,
		"GBP":     3,
		"CAD":     4,
		"CHF":     5,
		"UAH":     6,
		"JPY":     7,
	}
)

func (x Currency_Code) Enum() *Currency_Code {
	p := new(Currency_Code)
	*p = x
	return p
}

func (x Currency_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_beeswax_currency_currency_proto_enumTypes[0].Descriptor()
}

func (Currency_Code) Type() protoreflect.EnumType {
	return &file_beeswax_currency_currency_proto_enumTypes[0]
}

func (x Currency_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency_Code.Descriptor instead.
func (Currency_Code) EnumDescriptor() ([]byte, []int) {
	return file_beeswax_currency_currency_proto_rawDescGZIP(), []int{0, 0}
}

type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_beeswax_currency_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_currency_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_beeswax_currency_currency_proto_rawDescGZIP(), []int{0}
}

// Next id: 3
type ExchangeRateUSD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyCode  Currency_Code          `protobuf:"varint,1,opt,name=currency_code,json=currencyCode,proto3,enum=currency.Currency_Code" json:"currency_code,omitempty"`
	Rate          float64                `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRateUSD) Reset() {
	*x = ExchangeRateUSD{}
	mi := &file_beeswax_currency_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateUSD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateUSD) ProtoMessage() {}

func (x *ExchangeRateUSD) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_currency_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateUSD.ProtoReflect.Descriptor instead.
func (*ExchangeRateUSD) Descriptor() ([]byte, []int) {
	return file_beeswax_currency_currency_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeRateUSD) GetCurrencyCode() Currency_Code {
	if x != nil {
		return x.CurrencyCode
	}
	return Currency_UNKNOWN
}

func (x *ExchangeRateUSD) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

// Next id: 2
type CurrencyExchangeRateUSDTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rates         []*ExchangeRateUSD     `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyExchangeRateUSDTable) Reset() {
	*x = CurrencyExchangeRateUSDTable{}
	mi := &file_beeswax_currency_currency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyExchangeRateUSDTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyExchangeRateUSDTable) ProtoMessage() {}

func (x *CurrencyExchangeRateUSDTable) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_currency_currency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyExchangeRateUSDTable.ProtoReflect.Descriptor instead.
func (*CurrencyExchangeRateUSDTable) Descriptor() ([]byte, []int) {
	return file_beeswax_currency_currency_proto_rawDescGZIP(), []int{2}
}

func (x *CurrencyExchangeRateUSDTable) GetRates() []*ExchangeRateUSD {
	if x != nil {
		return x.Rates
	}
	return nil
}

// Next id: 3
// CurrencyAmount represents an amount of money in a local currency (micros).
type CurrencyAmount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// how much money
	Micros int64 `protobuf:"varint,1,opt,name=micros,proto3" json:"micros,omitempty"`
	// in what unit
	Currency      Currency_Code `protobuf:"varint,2,opt,name=currency,proto3,enum=currency.Currency_Code" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyAmount) Reset() {
	*x = CurrencyAmount{}
	mi := &file_beeswax_currency_currency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyAmount) ProtoMessage() {}

func (x *CurrencyAmount) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_currency_currency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyAmount.ProtoReflect.Descriptor instead.
func (*CurrencyAmount) Descriptor() ([]byte, []int) {
	return file_beeswax_currency_currency_proto_rawDescGZIP(), []int{3}
}

func (x *CurrencyAmount) GetMicros() int64 {
	if x != nil {
		return x.Micros
	}
	return 0
}

func (x *CurrencyAmount) GetCurrency() Currency_Code {
	if x != nil {
		return x.Currency
	}
	return Currency_UNKNOWN
}

// Next id: 3
// CurrencyTransaction represents an amount of
// currency at a particular exchange rate.
type CurrencyTransaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// how much money
	Amount *CurrencyAmount `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// exchange rate in effect at time of transaction
	Rate          float64 `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyTransaction) Reset() {
	*x = CurrencyTransaction{}
	mi := &file_beeswax_currency_currency_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyTransaction) ProtoMessage() {}

func (x *CurrencyTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_currency_currency_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyTransaction.ProtoReflect.Descriptor instead.
func (*CurrencyTransaction) Descriptor() ([]byte, []int) {
	return file_beeswax_currency_currency_proto_rawDescGZIP(), []int{4}
}

func (x *CurrencyTransaction) GetAmount() *CurrencyAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CurrencyTransaction) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

var File_beeswax_currency_currency_proto protoreflect.FileDescriptor

const file_beeswax_currency_currency_proto_rawDesc = "" +
	"\n" +
	"\x1fbeeswax/currency/currency.proto\x12\bcurrency\"^\n" +
	"\bCurrency\"R\n" +
	"\x04Code\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03USD\x10\x01\x12\a\n" +
	"\x03EUR\x10\x02\x12\a\n" +
	"\x03GBP\x10\x03\x12\a\n" +
	"\x03CAD\x10\x04\x12\a\n" +
	"\x03CHF\x10\x05\x12\a\n" +
	"\x03UAH\x10\x06\x12\a\n" +
	"\x03JPY\x10\a\"c\n" +
	"\x0fExchangeRateUSD\x12<\n" +
	"\rcurrency_code\x18\x01 \x01(\x0e2\x17.currency.Currency.CodeR\fcurrencyCode\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x01R\x04rate\"O\n" +
	"\x1cCurrencyExchangeRateUSDTable\x12/\n" +
	"\x05rates\x18\x01 \x03(\v2\x19.currency.ExchangeRateUSDR\x05rates\"]\n" +
	"\x0eCurrencyAmount\x12\x16\n" +
	"\x06micros\x18\x01 \x01(\x03R\x06micros\x123\n" +
	"\bcurrency\x18\x02 \x01(\x0e2\x17.currency.Currency.CodeR\bcurrency\"[\n" +
	"\x13CurrencyTransaction\x120\n" +
	"\x06amount\x18\x01 \x01(\v2\x18.currency.CurrencyAmountR\x06amount\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x01R\x04rateB\x12\n" +
	"\x10com.beeswax.baseb\x06proto3"

var (
	file_beeswax_currency_currency_proto_rawDescOnce sync.Once
	file_beeswax_currency_currency_proto_rawDescData []byte
)

func file_beeswax_currency_currency_proto_rawDescGZIP() []byte {
	file_beeswax_currency_currency_proto_rawDescOnce.Do(func() {
		file_beeswax_currency_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beeswax_currency_currency_proto_rawDesc), len(file_beeswax_currency_currency_proto_rawDesc)))
	})
	return file_beeswax_currency_currency_proto_rawDescData
}

var file_beeswax_currency_currency_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_beeswax_currency_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_beeswax_currency_currency_proto_goTypes = []any{
	(Currency_Code)(0),                   // 0: currency.Currency.Code
	(*Currency)(nil),                     // 1: currency.Currency
	(*ExchangeRateUSD)(nil),              // 2: currency.ExchangeRateUSD
	(*CurrencyExchangeRateUSDTable)(nil), // 3: currency.CurrencyExchangeRateUSDTable
	(*CurrencyAmount)(nil),               // 4: currency.CurrencyAmount
	(*CurrencyTransaction)(nil),          // 5: currency.CurrencyTransaction
}
var file_beeswax_currency_currency_proto_depIdxs = []int32{
	0, // 0: currency.ExchangeRateUSD.currency_code:type_name -> currency.Currency.Code
	2, // 1: currency.CurrencyExchangeRateUSDTable.rates:type_name -> currency.ExchangeRateUSD
	0, // 2: currency.CurrencyAmount.currency:type_name -> currency.Currency.Code
	4, // 3: currency.CurrencyTransaction.amount:type_name -> currency.CurrencyAmount
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_beeswax_currency_currency_proto_init() }
func file_beeswax_currency_currency_proto_init() {
	if File_beeswax_currency_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beeswax_currency_currency_proto_rawDesc), len(file_beeswax_currency_currency_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_beeswax_currency_currency_proto_goTypes,
		DependencyIndexes: file_beeswax_currency_currency_proto_depIdxs,
		EnumInfos:         file_beeswax_currency_currency_proto_enumTypes,
		MessageInfos:      file_beeswax_currency_currency_proto_msgTypes,
	}.Build()
	File_beeswax_currency_currency_proto = out.File
	file_beeswax_currency_currency_proto_goTypes = nil
	file_beeswax_currency_currency_proto_depIdxs = nil
}
