// Copyright 2015, Beeswax.IO Inc.
//
// Adcandidate represents a line item (along with its attributes) that
// is eligible to serve on a given bid request.
// Stinger determines the eligible line items and creatives and generates
// the adcandidate.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.3
// source: beeswax/bid/adcandidate.proto

package bid

import (
	currency "github.com/feed-mob/beeswax-api/beeswax/currency"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Next Tag: 9
type Bidding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only one of the strategies will be present.
	CpmStrategy    *Bidding_CpmStrategy    `protobuf:"bytes,1,opt,name=cpm_strategy,json=cpmStrategy" json:"cpm_strategy,omitempty"`
	CpcStrategy    *Bidding_CpcStrategy    `protobuf:"bytes,2,opt,name=cpc_strategy,json=cpcStrategy" json:"cpc_strategy,omitempty"`
	CustomStrategy *Bidding_CustomStrategy `protobuf:"bytes,4,opt,name=custom_strategy,json=customStrategy" json:"custom_strategy,omitempty"`
	Currency       *currency.Currency_Code `protobuf:"varint,5,opt,name=currency,enum=currency.Currency_Code" json:"currency,omitempty"`
	// The product of all eligible modifiers' multipliers.
	BidModifierMultipliersProduct *float32 `protobuf:"fixed32,6,opt,name=bid_modifier_multipliers_product,json=bidModifierMultipliersProduct,def=1" json:"bid_modifier_multipliers_product,omitempty"`
	MaxBidMicros                  *uint64  `protobuf:"varint,7,opt,name=max_bid_micros,json=maxBidMicros" json:"max_bid_micros,omitempty"`
	MinBidMicros                  *uint64  `protobuf:"varint,8,opt,name=min_bid_micros,json=minBidMicros" json:"min_bid_micros,omitempty"`
	// The following fields are for internal use by the bidding agents and
	// will not be set in the request or response.
	BidPriceMicros *uint64 `protobuf:"varint,3,opt,name=bid_price_micros,json=bidPriceMicros" json:"bid_price_micros,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

// Default values for Bidding fields.
const (
	Default_Bidding_BidModifierMultipliersProduct = float32(1)
)

func (x *Bidding) Reset() {
	*x = Bidding{}
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bidding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bidding) ProtoMessage() {}

func (x *Bidding) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bidding.ProtoReflect.Descriptor instead.
func (*Bidding) Descriptor() ([]byte, []int) {
	return file_beeswax_bid_adcandidate_proto_rawDescGZIP(), []int{0}
}

func (x *Bidding) GetCpmStrategy() *Bidding_CpmStrategy {
	if x != nil {
		return x.CpmStrategy
	}
	return nil
}

func (x *Bidding) GetCpcStrategy() *Bidding_CpcStrategy {
	if x != nil {
		return x.CpcStrategy
	}
	return nil
}

func (x *Bidding) GetCustomStrategy() *Bidding_CustomStrategy {
	if x != nil {
		return x.CustomStrategy
	}
	return nil
}

func (x *Bidding) GetCurrency() currency.Currency_Code {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return currency.Currency_Code(0)
}

func (x *Bidding) GetBidModifierMultipliersProduct() float32 {
	if x != nil && x.BidModifierMultipliersProduct != nil {
		return *x.BidModifierMultipliersProduct
	}
	return Default_Bidding_BidModifierMultipliersProduct
}

func (x *Bidding) GetMaxBidMicros() uint64 {
	if x != nil && x.MaxBidMicros != nil {
		return *x.MaxBidMicros
	}
	return 0
}

func (x *Bidding) GetMinBidMicros() uint64 {
	if x != nil && x.MinBidMicros != nil {
		return *x.MinBidMicros
	}
	return 0
}

func (x *Bidding) GetBidPriceMicros() uint64 {
	if x != nil && x.BidPriceMicros != nil {
		return *x.BidPriceMicros
	}
	return 0
}

// Pacing determines the rate of spend of the budget for a line item.
// When pace_delivery is set to true, the bidding agent is expected to pace
// the spend of the line item uniformly over its life time.
//
// Next Tag: 2
type Pacing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaceDelivery  *bool                  `protobuf:"varint,1,opt,name=pace_delivery,json=paceDelivery,def=0" json:"pace_delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Pacing fields.
const (
	Default_Pacing_PaceDelivery = bool(false)
)

func (x *Pacing) Reset() {
	*x = Pacing{}
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pacing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pacing) ProtoMessage() {}

func (x *Pacing) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pacing.ProtoReflect.Descriptor instead.
func (*Pacing) Descriptor() ([]byte, []int) {
	return file_beeswax_bid_adcandidate_proto_rawDescGZIP(), []int{1}
}

func (x *Pacing) GetPaceDelivery() bool {
	if x != nil && x.PaceDelivery != nil {
		return *x.PaceDelivery
	}
	return Default_Pacing_PaceDelivery
}

// FrequencyCapsInfo contains the information of a lineitem/campaign's
// frequency cap constraints and the user's impression history.
// The bidding agent will not receive adcandidates which are not
// eligible to bid when any of the lineitem/campaingn's frequency cap's
// limit is hit.
//
// Next Id: 4
type FrequencyCapsInfo struct {
	state        protoimpl.MessageState            `protogen:"open.v1"`
	FrequencyCap []*FrequencyCapsInfo_FrequencyCap `protobuf:"bytes,1,rep,name=frequency_cap,json=frequencyCap" json:"frequency_cap,omitempty"`
	// Deprecated: Marked as deprecated in beeswax/bid/adcandidate.proto.
	ImpTimestamps []uint32 `protobuf:"varint,2,rep,name=imp_timestamps,json=impTimestamps" json:"imp_timestamps,omitempty"`
	// The last rx timestamp in seconds when the ad was served for the
	// line_item/campaign and user combination in the past 30 days. It is
	// updated real-time per request. It will not be populated if the
	// line_item/campaign does not have any impression for the user in the past
	// 30 days.
	LastImpTimestamp *uint32 `protobuf:"varint,3,opt,name=last_imp_timestamp,json=lastImpTimestamp" json:"last_imp_timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FrequencyCapsInfo) Reset() {
	*x = FrequencyCapsInfo{}
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrequencyCapsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrequencyCapsInfo) ProtoMessage() {}

func (x *FrequencyCapsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrequencyCapsInfo.ProtoReflect.Descriptor instead.
func (*FrequencyCapsInfo) Descriptor() ([]byte, []int) {
	return file_beeswax_bid_adcandidate_proto_rawDescGZIP(), []int{2}
}

func (x *FrequencyCapsInfo) GetFrequencyCap() []*FrequencyCapsInfo_FrequencyCap {
	if x != nil {
		return x.FrequencyCap
	}
	return nil
}

// Deprecated: Marked as deprecated in beeswax/bid/adcandidate.proto.
func (x *FrequencyCapsInfo) GetImpTimestamps() []uint32 {
	if x != nil {
		return x.ImpTimestamps
	}
	return nil
}

func (x *FrequencyCapsInfo) GetLastImpTimestamp() uint32 {
	if x != nil && x.LastImpTimestamp != nil {
		return *x.LastImpTimestamp
	}
	return 0
}

// VendorFeesInfo contains the aggregrated amount and percent of a
// lineitem/campaign's vendor fees.
// Next Id: 3
type VendorFeesInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total_vendor_fees_transactions are grouped by currency.
	// vendor fees with the same currency are aggregrated into one
	// CurrencyTransaction object.
	// For example, if a lineitem/campaign has a vendor fees of 30 micros USD,
	// another of 20 micros USD, the other 40 micros GBP,
	// there will be two items in this field - one 50 micros USD,
	// the other 40 micros GBP. (CurrencyTransaction contains the real-time
	// conversion rate)
	// In rare conditions when currency conversion rate is not available,
	// total_vendor_fees_transactions.rate field will not be populated.
	TotalVendorFeesTransactions []*currency.CurrencyTransaction `protobuf:"bytes,1,rep,name=total_vendor_fees_transactions,json=totalVendorFeesTransactions" json:"total_vendor_fees_transactions,omitempty"`
	// total_fee_percent_micros is the sum of percent value in micros of all
	// percent type vendor fees.
	// For example, a line/campaign has a vendor fees at 5%, another 2%,
	// this field will be "7" in micros, i.e., 7000000
	TotalFeePercentMicros *int64 `protobuf:"varint,2,opt,name=total_fee_percent_micros,json=totalFeePercentMicros" json:"total_fee_percent_micros,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VendorFeesInfo) Reset() {
	*x = VendorFeesInfo{}
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorFeesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorFeesInfo) ProtoMessage() {}

func (x *VendorFeesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorFeesInfo.ProtoReflect.Descriptor instead.
func (*VendorFeesInfo) Descriptor() ([]byte, []int) {
	return file_beeswax_bid_adcandidate_proto_rawDescGZIP(), []int{3}
}

func (x *VendorFeesInfo) GetTotalVendorFeesTransactions() []*currency.CurrencyTransaction {
	if x != nil {
		return x.TotalVendorFeesTransactions
	}
	return nil
}

func (x *VendorFeesInfo) GetTotalFeePercentMicros() int64 {
	if x != nil && x.TotalFeePercentMicros != nil {
		return *x.TotalFeePercentMicros
	}
	return 0
}

// Adcandidate represents an eligible line item and its attributes.
// Stinger determines the eligible line items for a given request.
//
// Next Tag: 28
type Adcandidate struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	LineItemId            *uint64                `protobuf:"varint,1,opt,name=line_item_id,json=lineItemId" json:"line_item_id,omitempty"`
	CampaignId            *uint64                `protobuf:"varint,5,opt,name=campaign_id,json=campaignId" json:"campaign_id,omitempty"`
	AccountId             *uint64                `protobuf:"varint,6,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	AdvertiserId          *uint64                `protobuf:"varint,8,opt,name=advertiser_id,json=advertiserId" json:"advertiser_id,omitempty"`
	LineItemAlternativeId *string                `protobuf:"bytes,9,opt,name=line_item_alternative_id,json=lineItemAlternativeId" json:"line_item_alternative_id,omitempty"`
	BuzzKey               *string                `protobuf:"bytes,7,opt,name=buzz_key,json=buzzKey" json:"buzz_key,omitempty"`
	CreativeIds           []uint64               `protobuf:"varint,2,rep,name=creative_ids,json=creativeIds" json:"creative_ids,omitempty"`
	Bidding               *Bidding               `protobuf:"bytes,3,opt,name=bidding" json:"bidding,omitempty"`
	Pacing                *Pacing                `protobuf:"bytes,4,opt,name=pacing" json:"pacing,omitempty"`
	// This field wil be empty if the line_item does not have any frequency
	// cap associated with it.
	LineItemFrequencyCapsInfo *FrequencyCapsInfo `protobuf:"bytes,10,opt,name=line_item_frequency_caps_info,json=lineItemFrequencyCapsInfo" json:"line_item_frequency_caps_info,omitempty"`
	// This field wil be empty if the campaign does not have any frequency
	// cap associated with it.
	CampaignFrequencyCapsInfo *FrequencyCapsInfo `protobuf:"bytes,11,opt,name=campaign_frequency_caps_info,json=campaignFrequencyCapsInfo" json:"campaign_frequency_caps_info,omitempty"`
	LineItemVendorFeesInfo    *VendorFeesInfo    `protobuf:"bytes,12,opt,name=line_item_vendor_fees_info,json=lineItemVendorFeesInfo" json:"line_item_vendor_fees_info,omitempty"`
	CampaignVendorFeesInfo    *VendorFeesInfo    `protobuf:"bytes,13,opt,name=campaign_vendor_fees_info,json=campaignVendorFeesInfo" json:"campaign_vendor_fees_info,omitempty"`
	// This field will be populated if the line item is associated with
	// any experiment grouped by user.
	ExperimentUserTestGroupId *uint64  `protobuf:"varint,14,opt,name=experiment_user_test_group_id,json=experimentUserTestGroupId" json:"experiment_user_test_group_id,omitempty"`
	DealId                    *string  `protobuf:"bytes,15,opt,name=deal_id,json=dealId" json:"deal_id,omitempty"`
	FlightId                  *uint64  `protobuf:"varint,25,opt,name=flight_id,json=flightId" json:"flight_id,omitempty"`
	TargetedSegments          []string `protobuf:"bytes,27,rep,name=targeted_segments,json=targetedSegments" json:"targeted_segments,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Adcandidate) Reset() {
	*x = Adcandidate{}
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Adcandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Adcandidate) ProtoMessage() {}

func (x *Adcandidate) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Adcandidate.ProtoReflect.Descriptor instead.
func (*Adcandidate) Descriptor() ([]byte, []int) {
	return file_beeswax_bid_adcandidate_proto_rawDescGZIP(), []int{4}
}

func (x *Adcandidate) GetLineItemId() uint64 {
	if x != nil && x.LineItemId != nil {
		return *x.LineItemId
	}
	return 0
}

func (x *Adcandidate) GetCampaignId() uint64 {
	if x != nil && x.CampaignId != nil {
		return *x.CampaignId
	}
	return 0
}

func (x *Adcandidate) GetAccountId() uint64 {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return 0
}

func (x *Adcandidate) GetAdvertiserId() uint64 {
	if x != nil && x.AdvertiserId != nil {
		return *x.AdvertiserId
	}
	return 0
}

func (x *Adcandidate) GetLineItemAlternativeId() string {
	if x != nil && x.LineItemAlternativeId != nil {
		return *x.LineItemAlternativeId
	}
	return ""
}

func (x *Adcandidate) GetBuzzKey() string {
	if x != nil && x.BuzzKey != nil {
		return *x.BuzzKey
	}
	return ""
}

func (x *Adcandidate) GetCreativeIds() []uint64 {
	if x != nil {
		return x.CreativeIds
	}
	return nil
}

func (x *Adcandidate) GetBidding() *Bidding {
	if x != nil {
		return x.Bidding
	}
	return nil
}

func (x *Adcandidate) GetPacing() *Pacing {
	if x != nil {
		return x.Pacing
	}
	return nil
}

func (x *Adcandidate) GetLineItemFrequencyCapsInfo() *FrequencyCapsInfo {
	if x != nil {
		return x.LineItemFrequencyCapsInfo
	}
	return nil
}

func (x *Adcandidate) GetCampaignFrequencyCapsInfo() *FrequencyCapsInfo {
	if x != nil {
		return x.CampaignFrequencyCapsInfo
	}
	return nil
}

func (x *Adcandidate) GetLineItemVendorFeesInfo() *VendorFeesInfo {
	if x != nil {
		return x.LineItemVendorFeesInfo
	}
	return nil
}

func (x *Adcandidate) GetCampaignVendorFeesInfo() *VendorFeesInfo {
	if x != nil {
		return x.CampaignVendorFeesInfo
	}
	return nil
}

func (x *Adcandidate) GetExperimentUserTestGroupId() uint64 {
	if x != nil && x.ExperimentUserTestGroupId != nil {
		return *x.ExperimentUserTestGroupId
	}
	return 0
}

func (x *Adcandidate) GetDealId() string {
	if x != nil && x.DealId != nil {
		return *x.DealId
	}
	return ""
}

func (x *Adcandidate) GetFlightId() uint64 {
	if x != nil && x.FlightId != nil {
		return *x.FlightId
	}
	return 0
}

func (x *Adcandidate) GetTargetedSegments() []string {
	if x != nil {
		return x.TargetedSegments
	}
	return nil
}

// CPM: Always bid a flat price on all matched requests.
type Bidding_CpmStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlatBidMicros *uint64                `protobuf:"varint,1,opt,name=flat_bid_micros,json=flatBidMicros" json:"flat_bid_micros,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bidding_CpmStrategy) Reset() {
	*x = Bidding_CpmStrategy{}
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bidding_CpmStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bidding_CpmStrategy) ProtoMessage() {}

func (x *Bidding_CpmStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bidding_CpmStrategy.ProtoReflect.Descriptor instead.
func (*Bidding_CpmStrategy) Descriptor() ([]byte, []int) {
	return file_beeswax_bid_adcandidate_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Bidding_CpmStrategy) GetFlatBidMicros() uint64 {
	if x != nil && x.FlatBidMicros != nil {
		return *x.FlatBidMicros
	}
	return 0
}

// CPC: Optimize towards a cost per click goal.
type Bidding_CpcStrategy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated, use Bidding.max_bid_micros instead.
	//
	// Deprecated: Marked as deprecated in beeswax/bid/adcandidate.proto.
	MaxBidMicros     *uint64 `protobuf:"varint,1,opt,name=max_bid_micros,json=maxBidMicros" json:"max_bid_micros,omitempty"`
	EcpcTargetMicros *uint64 `protobuf:"varint,2,opt,name=ecpc_target_micros,json=ecpcTargetMicros" json:"ecpc_target_micros,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Bidding_CpcStrategy) Reset() {
	*x = Bidding_CpcStrategy{}
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bidding_CpcStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bidding_CpcStrategy) ProtoMessage() {}

func (x *Bidding_CpcStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bidding_CpcStrategy.ProtoReflect.Descriptor instead.
func (*Bidding_CpcStrategy) Descriptor() ([]byte, []int) {
	return file_beeswax_bid_adcandidate_proto_rawDescGZIP(), []int{0, 1}
}

// Deprecated: Marked as deprecated in beeswax/bid/adcandidate.proto.
func (x *Bidding_CpcStrategy) GetMaxBidMicros() uint64 {
	if x != nil && x.MaxBidMicros != nil {
		return *x.MaxBidMicros
	}
	return 0
}

func (x *Bidding_CpcStrategy) GetEcpcTargetMicros() uint64 {
	if x != nil && x.EcpcTargetMicros != nil {
		return *x.EcpcTargetMicros
	}
	return 0
}

// Custom strategy is defined using Buzz API.
// Customers can define many different strategies and identify them using
// a name.
// Further, customers can associate multiple key, values with a strategy
// that are made available in the matching Adcandidate.
// Customers can use the key,values to implement their own optimization.
type Bidding_CustomStrategy struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Name          *string                          `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	CustomParams  []*Bidding_CustomStrategy_Params `protobuf:"bytes,2,rep,name=custom_params,json=customParams" json:"custom_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bidding_CustomStrategy) Reset() {
	*x = Bidding_CustomStrategy{}
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bidding_CustomStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bidding_CustomStrategy) ProtoMessage() {}

func (x *Bidding_CustomStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bidding_CustomStrategy.ProtoReflect.Descriptor instead.
func (*Bidding_CustomStrategy) Descriptor() ([]byte, []int) {
	return file_beeswax_bid_adcandidate_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Bidding_CustomStrategy) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Bidding_CustomStrategy) GetCustomParams() []*Bidding_CustomStrategy_Params {
	if x != nil {
		return x.CustomParams
	}
	return nil
}

type Bidding_CustomStrategy_Params struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bidding_CustomStrategy_Params) Reset() {
	*x = Bidding_CustomStrategy_Params{}
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bidding_CustomStrategy_Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bidding_CustomStrategy_Params) ProtoMessage() {}

func (x *Bidding_CustomStrategy_Params) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bidding_CustomStrategy_Params.ProtoReflect.Descriptor instead.
func (*Bidding_CustomStrategy_Params) Descriptor() ([]byte, []int) {
	return file_beeswax_bid_adcandidate_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Bidding_CustomStrategy_Params) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *Bidding_CustomStrategy_Params) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

// FrequencyCap contains the frequency constraints for a given user to not
// view the ad more than `max_impressions` times within a duration of
// `duration_seconds`, and the actual impression counts within the duration
// for the user as in `current_impression_count`.
// `max_impressions` and `duration_seconds` are defined using Buzz API, and
// `current_impression_count` is populated real-time per request.
// E.g. If a line item specifies hourly frequency cap
// constraints of 10 impression/user, and it has had impressions for the
// past hour, the value will be
// {max_impressions = 10, duration_secs = 3600, current_impression_count = 2}.
//
// Next Id: 4
type FrequencyCapsInfo_FrequencyCap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Allowed number of impressions in the duration .
	MaxImpressions *uint32 `protobuf:"varint,1,opt,name=max_impressions,json=maxImpressions" json:"max_impressions,omitempty"`
	// The duration (in second) in which max_impressions should not be exceeded.
	DurationSeconds *uint32 `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds" json:"duration_seconds,omitempty"`
	// Actual impression numbers served in the duration.
	CurrentImpressionCount *uint32 `protobuf:"varint,3,opt,name=current_impression_count,json=currentImpressionCount" json:"current_impression_count,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FrequencyCapsInfo_FrequencyCap) Reset() {
	*x = FrequencyCapsInfo_FrequencyCap{}
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrequencyCapsInfo_FrequencyCap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrequencyCapsInfo_FrequencyCap) ProtoMessage() {}

func (x *FrequencyCapsInfo_FrequencyCap) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_bid_adcandidate_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrequencyCapsInfo_FrequencyCap.ProtoReflect.Descriptor instead.
func (*FrequencyCapsInfo_FrequencyCap) Descriptor() ([]byte, []int) {
	return file_beeswax_bid_adcandidate_proto_rawDescGZIP(), []int{2, 0}
}

func (x *FrequencyCapsInfo_FrequencyCap) GetMaxImpressions() uint32 {
	if x != nil && x.MaxImpressions != nil {
		return *x.MaxImpressions
	}
	return 0
}

func (x *FrequencyCapsInfo_FrequencyCap) GetDurationSeconds() uint32 {
	if x != nil && x.DurationSeconds != nil {
		return *x.DurationSeconds
	}
	return 0
}

func (x *FrequencyCapsInfo_FrequencyCap) GetCurrentImpressionCount() uint32 {
	if x != nil && x.CurrentImpressionCount != nil {
		return *x.CurrentImpressionCount
	}
	return 0
}

var File_beeswax_bid_adcandidate_proto protoreflect.FileDescriptor

const file_beeswax_bid_adcandidate_proto_rawDesc = "" +
	"\n" +
	"\x1dbeeswax/bid/adcandidate.proto\x12\x03bid\x1a\x1fbeeswax/currency/currency.proto\"\x80\x06\n" +
	"\aBidding\x12;\n" +
	"\fcpm_strategy\x18\x01 \x01(\v2\x18.bid.Bidding.CpmStrategyR\vcpmStrategy\x12;\n" +
	"\fcpc_strategy\x18\x02 \x01(\v2\x18.bid.Bidding.CpcStrategyR\vcpcStrategy\x12D\n" +
	"\x0fcustom_strategy\x18\x04 \x01(\v2\x1b.bid.Bidding.CustomStrategyR\x0ecustomStrategy\x123\n" +
	"\bcurrency\x18\x05 \x01(\x0e2\x17.currency.Currency.CodeR\bcurrency\x12J\n" +
	" bid_modifier_multipliers_product\x18\x06 \x01(\x02:\x011R\x1dbidModifierMultipliersProduct\x12$\n" +
	"\x0emax_bid_micros\x18\a \x01(\x04R\fmaxBidMicros\x12$\n" +
	"\x0emin_bid_micros\x18\b \x01(\x04R\fminBidMicros\x12(\n" +
	"\x10bid_price_micros\x18\x03 \x01(\x04R\x0ebidPriceMicros\x1a5\n" +
	"\vCpmStrategy\x12&\n" +
	"\x0fflat_bid_micros\x18\x01 \x01(\x04R\rflatBidMicros\x1ae\n" +
	"\vCpcStrategy\x12(\n" +
	"\x0emax_bid_micros\x18\x01 \x01(\x04B\x02\x18\x01R\fmaxBidMicros\x12,\n" +
	"\x12ecpc_target_micros\x18\x02 \x01(\x04R\x10ecpcTargetMicros\x1a\x9f\x01\n" +
	"\x0eCustomStrategy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12G\n" +
	"\rcustom_params\x18\x02 \x03(\v2\".bid.Bidding.CustomStrategy.ParamsR\fcustomParams\x1a0\n" +
	"\x06Params\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"4\n" +
	"\x06Pacing\x12*\n" +
	"\rpace_delivery\x18\x01 \x01(\b:\x05falseR\fpaceDelivery\"\xd5\x02\n" +
	"\x11FrequencyCapsInfo\x12H\n" +
	"\rfrequency_cap\x18\x01 \x03(\v2#.bid.FrequencyCapsInfo.FrequencyCapR\ffrequencyCap\x12)\n" +
	"\x0eimp_timestamps\x18\x02 \x03(\rB\x02\x18\x01R\rimpTimestamps\x12,\n" +
	"\x12last_imp_timestamp\x18\x03 \x01(\rR\x10lastImpTimestamp\x1a\x9c\x01\n" +
	"\fFrequencyCap\x12'\n" +
	"\x0fmax_impressions\x18\x01 \x01(\rR\x0emaxImpressions\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\rR\x0fdurationSeconds\x128\n" +
	"\x18current_impression_count\x18\x03 \x01(\rR\x16currentImpressionCount\"\xad\x01\n" +
	"\x0eVendorFeesInfo\x12b\n" +
	"\x1etotal_vendor_fees_transactions\x18\x01 \x03(\v2\x1d.currency.CurrencyTransactionR\x1btotalVendorFeesTransactions\x127\n" +
	"\x18total_fee_percent_micros\x18\x02 \x01(\x03R\x15totalFeePercentMicros\"\xd1\x06\n" +
	"\vAdcandidate\x12 \n" +
	"\fline_item_id\x18\x01 \x01(\x04R\n" +
	"lineItemId\x12\x1f\n" +
	"\vcampaign_id\x18\x05 \x01(\x04R\n" +
	"campaignId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x06 \x01(\x04R\taccountId\x12#\n" +
	"\radvertiser_id\x18\b \x01(\x04R\fadvertiserId\x127\n" +
	"\x18line_item_alternative_id\x18\t \x01(\tR\x15lineItemAlternativeId\x12\x19\n" +
	"\bbuzz_key\x18\a \x01(\tR\abuzzKey\x12!\n" +
	"\fcreative_ids\x18\x02 \x03(\x04R\vcreativeIds\x12&\n" +
	"\abidding\x18\x03 \x01(\v2\f.bid.BiddingR\abidding\x12#\n" +
	"\x06pacing\x18\x04 \x01(\v2\v.bid.PacingR\x06pacing\x12X\n" +
	"\x1dline_item_frequency_caps_info\x18\n" +
	" \x01(\v2\x16.bid.FrequencyCapsInfoR\x19lineItemFrequencyCapsInfo\x12W\n" +
	"\x1ccampaign_frequency_caps_info\x18\v \x01(\v2\x16.bid.FrequencyCapsInfoR\x19campaignFrequencyCapsInfo\x12O\n" +
	"\x1aline_item_vendor_fees_info\x18\f \x01(\v2\x13.bid.VendorFeesInfoR\x16lineItemVendorFeesInfo\x12N\n" +
	"\x19campaign_vendor_fees_info\x18\r \x01(\v2\x13.bid.VendorFeesInfoR\x16campaignVendorFeesInfo\x12@\n" +
	"\x1dexperiment_user_test_group_id\x18\x0e \x01(\x04R\x19experimentUserTestGroupId\x12\x17\n" +
	"\adeal_id\x18\x0f \x01(\tR\x06dealId\x12\x1b\n" +
	"\tflight_id\x18\x19 \x01(\x04R\bflightId\x12+\n" +
	"\x11targeted_segments\x18\x1b \x03(\tR\x10targetedSegmentsB\x11\n" +
	"\x0fcom.beeswax.bid"

var (
	file_beeswax_bid_adcandidate_proto_rawDescOnce sync.Once
	file_beeswax_bid_adcandidate_proto_rawDescData []byte
)

func file_beeswax_bid_adcandidate_proto_rawDescGZIP() []byte {
	file_beeswax_bid_adcandidate_proto_rawDescOnce.Do(func() {
		file_beeswax_bid_adcandidate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beeswax_bid_adcandidate_proto_rawDesc), len(file_beeswax_bid_adcandidate_proto_rawDesc)))
	})
	return file_beeswax_bid_adcandidate_proto_rawDescData
}

var file_beeswax_bid_adcandidate_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_beeswax_bid_adcandidate_proto_goTypes = []any{
	(*Bidding)(nil),                        // 0: bid.Bidding
	(*Pacing)(nil),                         // 1: bid.Pacing
	(*FrequencyCapsInfo)(nil),              // 2: bid.FrequencyCapsInfo
	(*VendorFeesInfo)(nil),                 // 3: bid.VendorFeesInfo
	(*Adcandidate)(nil),                    // 4: bid.Adcandidate
	(*Bidding_CpmStrategy)(nil),            // 5: bid.Bidding.CpmStrategy
	(*Bidding_CpcStrategy)(nil),            // 6: bid.Bidding.CpcStrategy
	(*Bidding_CustomStrategy)(nil),         // 7: bid.Bidding.CustomStrategy
	(*Bidding_CustomStrategy_Params)(nil),  // 8: bid.Bidding.CustomStrategy.Params
	(*FrequencyCapsInfo_FrequencyCap)(nil), // 9: bid.FrequencyCapsInfo.FrequencyCap
	(currency.Currency_Code)(0),            // 10: currency.Currency.Code
	(*currency.CurrencyTransaction)(nil),   // 11: currency.CurrencyTransaction
}
var file_beeswax_bid_adcandidate_proto_depIdxs = []int32{
	5,  // 0: bid.Bidding.cpm_strategy:type_name -> bid.Bidding.CpmStrategy
	6,  // 1: bid.Bidding.cpc_strategy:type_name -> bid.Bidding.CpcStrategy
	7,  // 2: bid.Bidding.custom_strategy:type_name -> bid.Bidding.CustomStrategy
	10, // 3: bid.Bidding.currency:type_name -> currency.Currency.Code
	9,  // 4: bid.FrequencyCapsInfo.frequency_cap:type_name -> bid.FrequencyCapsInfo.FrequencyCap
	11, // 5: bid.VendorFeesInfo.total_vendor_fees_transactions:type_name -> currency.CurrencyTransaction
	0,  // 6: bid.Adcandidate.bidding:type_name -> bid.Bidding
	1,  // 7: bid.Adcandidate.pacing:type_name -> bid.Pacing
	2,  // 8: bid.Adcandidate.line_item_frequency_caps_info:type_name -> bid.FrequencyCapsInfo
	2,  // 9: bid.Adcandidate.campaign_frequency_caps_info:type_name -> bid.FrequencyCapsInfo
	3,  // 10: bid.Adcandidate.line_item_vendor_fees_info:type_name -> bid.VendorFeesInfo
	3,  // 11: bid.Adcandidate.campaign_vendor_fees_info:type_name -> bid.VendorFeesInfo
	8,  // 12: bid.Bidding.CustomStrategy.custom_params:type_name -> bid.Bidding.CustomStrategy.Params
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_beeswax_bid_adcandidate_proto_init() }
func file_beeswax_bid_adcandidate_proto_init() {
	if File_beeswax_bid_adcandidate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beeswax_bid_adcandidate_proto_rawDesc), len(file_beeswax_bid_adcandidate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_beeswax_bid_adcandidate_proto_goTypes,
		DependencyIndexes: file_beeswax_bid_adcandidate_proto_depIdxs,
		MessageInfos:      file_beeswax_bid_adcandidate_proto_msgTypes,
	}.Build()
	File_beeswax_bid_adcandidate_proto = out.File
	file_beeswax_bid_adcandidate_proto_goTypes = nil
	file_beeswax_bid_adcandidate_proto_depIdxs = nil
}
