// Copyright 2020, Beeswax.IO Inc.
// Protocol buffer defining ghost bidding attributes of an adgroup

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.3
// source: beeswax/adgroup/ghost_bidding.proto

package adgroup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Next Tag: 2
type GhostBidding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// if the bid is a ghost bid. If true, the bid will be logged but will NOT be submitted to exchanges.
	IsGhostBid    *bool `protobuf:"varint,1,req,name=is_ghost_bid,json=isGhostBid" json:"is_ghost_bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GhostBidding) Reset() {
	*x = GhostBidding{}
	mi := &file_beeswax_adgroup_ghost_bidding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GhostBidding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GhostBidding) ProtoMessage() {}

func (x *GhostBidding) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_adgroup_ghost_bidding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GhostBidding.ProtoReflect.Descriptor instead.
func (*GhostBidding) Descriptor() ([]byte, []int) {
	return file_beeswax_adgroup_ghost_bidding_proto_rawDescGZIP(), []int{0}
}

func (x *GhostBidding) GetIsGhostBid() bool {
	if x != nil && x.IsGhostBid != nil {
		return *x.IsGhostBid
	}
	return false
}

var File_beeswax_adgroup_ghost_bidding_proto protoreflect.FileDescriptor

const file_beeswax_adgroup_ghost_bidding_proto_rawDesc = "" +
	"\n" +
	"#beeswax/adgroup/ghost_bidding.proto\x12\aadgroup\"0\n" +
	"\fGhostBidding\x12 \n" +
	"\fis_ghost_bid\x18\x01 \x02(\bR\n" +
	"isGhostBidB\x18\n" +
	"\x13com.beeswax.adgroup\xf8\x01\x01"

var (
	file_beeswax_adgroup_ghost_bidding_proto_rawDescOnce sync.Once
	file_beeswax_adgroup_ghost_bidding_proto_rawDescData []byte
)

func file_beeswax_adgroup_ghost_bidding_proto_rawDescGZIP() []byte {
	file_beeswax_adgroup_ghost_bidding_proto_rawDescOnce.Do(func() {
		file_beeswax_adgroup_ghost_bidding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beeswax_adgroup_ghost_bidding_proto_rawDesc), len(file_beeswax_adgroup_ghost_bidding_proto_rawDesc)))
	})
	return file_beeswax_adgroup_ghost_bidding_proto_rawDescData
}

var file_beeswax_adgroup_ghost_bidding_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_beeswax_adgroup_ghost_bidding_proto_goTypes = []any{
	(*GhostBidding)(nil), // 0: adgroup.GhostBidding
}
var file_beeswax_adgroup_ghost_bidding_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_beeswax_adgroup_ghost_bidding_proto_init() }
func file_beeswax_adgroup_ghost_bidding_proto_init() {
	if File_beeswax_adgroup_ghost_bidding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beeswax_adgroup_ghost_bidding_proto_rawDesc), len(file_beeswax_adgroup_ghost_bidding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_beeswax_adgroup_ghost_bidding_proto_goTypes,
		DependencyIndexes: file_beeswax_adgroup_ghost_bidding_proto_depIdxs,
		MessageInfos:      file_beeswax_adgroup_ghost_bidding_proto_msgTypes,
	}.Build()
	File_beeswax_adgroup_ghost_bidding_proto = out.File
	file_beeswax_adgroup_ghost_bidding_proto_goTypes = nil
	file_beeswax_adgroup_ghost_bidding_proto_depIdxs = nil
}
