// Copyright 2022, Beeswax.IO Inc.
//
// Protocol buffer defining vendor fees

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.3
// source: beeswax/adgroup/vendor_fee.proto

package adgroup

import (
	currency "github.com/feed-mob/beeswax-api/beeswax/currency"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VendorFeesInfo contains the aggregrated amount and percent of a
// lineitem/campaign's vendor fees.
// Next Id: 3
type VendorFeesInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total_vendor_fees_transactions are grouped by currency.
	// vendor fees with the same currency are aggregrated into one
	// CurrencyAmount object.
	// For example, if a lineitem/campaign has a vendor fees of 30 micros USD,
	// another of 20 micros USD, the other 40 micros GBP,
	// there will be two items in this field - one 50 micros USD,
	// the other 40 micros GBP.
	TotalVendorFeesAmounts []*currency.CurrencyAmount `protobuf:"bytes,1,rep,name=total_vendor_fees_amounts,json=totalVendorFeesAmounts" json:"total_vendor_fees_amounts,omitempty"`
	// total_fee_percent_micros is the sum of percent value in micros of all
	// percent type vendor fees.
	// For example, a line/campaign has a vendor fees at 5%, another 2%,
	// this field will be "7" in micros, i.e., 7000000
	TotalFeePercentMicros *int64 `protobuf:"varint,2,opt,name=total_fee_percent_micros,json=totalFeePercentMicros" json:"total_fee_percent_micros,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VendorFeesInfo) Reset() {
	*x = VendorFeesInfo{}
	mi := &file_beeswax_adgroup_vendor_fee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorFeesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorFeesInfo) ProtoMessage() {}

func (x *VendorFeesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_adgroup_vendor_fee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorFeesInfo.ProtoReflect.Descriptor instead.
func (*VendorFeesInfo) Descriptor() ([]byte, []int) {
	return file_beeswax_adgroup_vendor_fee_proto_rawDescGZIP(), []int{0}
}

func (x *VendorFeesInfo) GetTotalVendorFeesAmounts() []*currency.CurrencyAmount {
	if x != nil {
		return x.TotalVendorFeesAmounts
	}
	return nil
}

func (x *VendorFeesInfo) GetTotalFeePercentMicros() int64 {
	if x != nil && x.TotalFeePercentMicros != nil {
		return *x.TotalFeePercentMicros
	}
	return 0
}

var File_beeswax_adgroup_vendor_fee_proto protoreflect.FileDescriptor

const file_beeswax_adgroup_vendor_fee_proto_rawDesc = "" +
	"\n" +
	" beeswax/adgroup/vendor_fee.proto\x12\aadgroup\x1a\x1fbeeswax/currency/currency.proto\"\x9e\x01\n" +
	"\x0eVendorFeesInfo\x12S\n" +
	"\x19total_vendor_fees_amounts\x18\x01 \x03(\v2\x18.currency.CurrencyAmountR\x16totalVendorFeesAmounts\x127\n" +
	"\x18total_fee_percent_micros\x18\x02 \x01(\x03R\x15totalFeePercentMicrosB\x18\n" +
	"\x13com.beeswax.adgroup\xf8\x01\x01"

var (
	file_beeswax_adgroup_vendor_fee_proto_rawDescOnce sync.Once
	file_beeswax_adgroup_vendor_fee_proto_rawDescData []byte
)

func file_beeswax_adgroup_vendor_fee_proto_rawDescGZIP() []byte {
	file_beeswax_adgroup_vendor_fee_proto_rawDescOnce.Do(func() {
		file_beeswax_adgroup_vendor_fee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beeswax_adgroup_vendor_fee_proto_rawDesc), len(file_beeswax_adgroup_vendor_fee_proto_rawDesc)))
	})
	return file_beeswax_adgroup_vendor_fee_proto_rawDescData
}

var file_beeswax_adgroup_vendor_fee_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_beeswax_adgroup_vendor_fee_proto_goTypes = []any{
	(*VendorFeesInfo)(nil),          // 0: adgroup.VendorFeesInfo
	(*currency.CurrencyAmount)(nil), // 1: currency.CurrencyAmount
}
var file_beeswax_adgroup_vendor_fee_proto_depIdxs = []int32{
	1, // 0: adgroup.VendorFeesInfo.total_vendor_fees_amounts:type_name -> currency.CurrencyAmount
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_beeswax_adgroup_vendor_fee_proto_init() }
func file_beeswax_adgroup_vendor_fee_proto_init() {
	if File_beeswax_adgroup_vendor_fee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beeswax_adgroup_vendor_fee_proto_rawDesc), len(file_beeswax_adgroup_vendor_fee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_beeswax_adgroup_vendor_fee_proto_goTypes,
		DependencyIndexes: file_beeswax_adgroup_vendor_fee_proto_depIdxs,
		MessageInfos:      file_beeswax_adgroup_vendor_fee_proto_msgTypes,
	}.Build()
	File_beeswax_adgroup_vendor_fee_proto = out.File
	file_beeswax_adgroup_vendor_fee_proto_goTypes = nil
	file_beeswax_adgroup_vendor_fee_proto_depIdxs = nil
}
